#ifndef CONFIG_H
#define CONFIG_H

#include "colors.h"

#define SNAKE_BODY_SYM C_DARK_GREEN "@" C_DEFAULT
#define FOOD_SYM C_DARK_RED "#" C_DEFAULT
#define EMPTY_SYM " "

#define DEFAULT_BOARD_WIDTH 20
#define DEFAULT_BOARD_HEIGHT 10

#define SLEEP_BETWEEN_FRAMES_MS 100
#define MAX_KEYBOARD_INPUT_WAIT_TIME_MS 50
#endif